### ISSUE TITLE
ArgumentError: invalid byte sequence in US-ASCII on v2.2.0 in Docker

### ISSUE THREAD

**Issue by jamesottaway** [ffaker/ffaker#277]
It looks like `lib/ffaker/name_ua.rb` is encoded as ASCII, not UTF-8.

```
❯ docker run --rm -it ruby:2.3.1 bash
root@dc8455d6bc16:/# gem install ffaker -v '2.2.0'
Fetching: ffaker-2.2.0.gem (100%)
Successfully installed ffaker-2.2.0
1 gem installed
root@dc8455d6bc16:/# irb -r ffaker
/usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/utils/module_utils.rb:15:in `split': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/utils/module_utils.rb:15:in `const_missing'
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb:10:in `<module:NameUA>'
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb:6:in `<module:FFaker>'
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:33:in `block in <module:FFaker>'
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:32:in `each'
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:32:in `<module:FFaker>'
        from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /usr/local/lib/ruby/2.3.0/irb/init.rb:281:in `block in load_modules'
        from /usr/local/lib/ruby/2.3.0/irb/init.rb:279:in `each'
        from /usr/local/lib/ruby/2.3.0/irb/init.rb:279:in `load_modules'
        from /usr/local/lib/ruby/2.3.0/irb/init.rb:21:in `setup'
        from /usr/local/lib/ruby/2.3.0/irb.rb:378:in `start'
        from /usr/local/bin/irb:11:in `<main>'
root@dc8455d6bc16:/# file /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb
/usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb: Ruby module source, ASCII text
```

**Comment by oliworx** [comment]
I get the same error on GiltLab CI:
```
/usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/utils/module_utils.rb:15:in `split': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/utils/module_utils.rb:15:in `const_missing'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb:10:in `<module:NameUA>'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb:6:in `<module:FFaker>'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker/name_ua.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:33:in `require'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:33:in `block in <module:FFaker>'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:32:in `each'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:32:in `<module:FFaker>'
	from /usr/local/bundle/gems/ffaker-2.2.0/lib/ffaker.rb:1:in `<top (required)>'
```

**Comment by Kukunin** [comment]
The same for me, rolling back to 2.1.0 resolved problem

**Comment by pawelma** [comment]
Did you tried to use `export LC_ALL=en_US.UTF-8` command before running your code?

**Comment by mikesive** [comment]
Getting the same issue, I tried LC_ALL=en_US.UTF-8, which didn't work. I downgraded as @Kukunin suggested and the problem went away.

**Comment by zedtux** [comment]
Setting the following fixed the issue to me:

```
export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

**Comment by marocchino** [comment]
I checked file encoding of our project but, did not found strange things.
As ffaker use utf-8, It looks obvious to have to set lang.
but, seems docker team does not want to change default value.
- https://github.com/docker-library/docs/blob/master/ruby/content.md#encoding
- https://github.com/docker-library/ruby/issues/45 

For now, you need to set encoding explicitly like this:
```
$ docker run --rm -it -e LANG=C.UTF-8 ruby:2.4.0 bash
root@fee70e00af3c:/# gem install ffaker
Fetching: ffaker-2.4.0.gem (100%)
Successfully installed ffaker-2.4.0
1 gem installed
root@fee70e00af3c:/# irb -r ffaker
```
