### ISSUE TITLE
Uninitialized constant FFaker

### ISSUE THREAD

**Issue by SagareGanesh** [ffaker/ffaker#295]
When i trying to access FFaker on console, it gives me following error.

`2.1.0 :001 > FFaker`
` NameError: uninitialized constant FFaker`
 `from (irb):1`
`from ruby-2.1.0/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in 'start'`
`from ruby-2.1.0/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in 'start'`
`from ruby-2.1.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in 'console'`
`from ruby-2.1.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in 'run_command!'`
`from ruby-2.1.0/gems/railties-4.1.10/lib/rails/commands.rb:17:in '<top (required)>'`
`from bin/rails:4:in 'require'`
`from bin/rails:4:in '<main>'`

**Comment by SagareGanesh** [comment]
Issue resolved, I have updated my ffaker gem version. old gem version is 1.22.1 which is too old.
I have updated to 2.2.0 . Now its working fine.
