### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by SteveRedka** [ffaker/ffaker#495]
Running `ruby test/test_lorem.rb` results in:

```ruby
Traceback (most recent call last):
	3: from test/test_lorem.rb:5:in `<main>'
	2: from test/test_lorem.rb:9:in `<class:TestLorem>'
	1: from /home/me/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/me/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffaker/lorem (LoadError)
```

Also `gem install ffaker` makes all tests green, regardless of any changes made to files.

**Comment by SteveRedka** [comment]
I think I found what causes it?

#496 

`autoload` doesn't load files relative to file's location. But maybe I'm missing something;  autoload was added 3 years ago, and I'm the first person to run into this problem. 

I also noticed a lot of broken tests; maybe I'll patch some of them later

**Comment by SteveRedka** [comment]
For all tests:
```rake test```

For individual test:
```ruby
rake test TEST=test/test_lorem_br.rb
```
