### ISSUE TITLE
Reference is deleted.

### ISSUE THREAD

**Issue by marocchino** [ffaker/ffaker#544]
https://github.com/ffaker/ffaker/commit/3e3b1edbaf25da346e936e31ae719d0e12188ffb

https://github.com/ffaker/ffaker/actions/runs/6167496433/job/16738549676
```
Run bundle exec rake reference
/home/runner/work/ffaker/ffaker/lib/ffaker/utils/module_utils.rb:17:in `const_missing': uninitialized constant FFaker::Version (NameError)
Did you mean?  FFaker::VERSION
	from ./scripts/reference.rb:22:in `const_get'
	from ./scripts/reference.rb:22:in `block in faker_modules'
	from ./scripts/reference.rb:22:in `select'
	from ./scripts/reference.rb:22:in `faker_modules'
	from ./scripts/reference.rb:[5](https://github.com/ffaker/ffaker/actions/runs/6167496433/job/16738549676#step:4:6)3:in `<main>'
```

**Comment by marocchino** [comment]
2ea3bcf
