### ISSUE TITLE
"uninitialized constant: Faker::Unit" with rbx 2.1.1 and faker 1.22.0

### ISSUE THREAD

**Issue by fwoeck** [ffaker/ffaker#97]
Hi, with rbx 2.1.1 I'm getting this error, when I require faker 1.22.0:

```
2.1 :001 > require 'ffaker'
NameError: Missing or uninitialized constant: Faker::Unit
        from kernel/common/module.rb:677:in `const_missing'
        from ./vendor/bundle/rbx/2.1/gems/ffaker-1.22.0/lib/ffaker/utils/module_utils.rb:11:in `const_missing'
```

**Comment by deepakm-webonise** [comment]
@EmmanuelOga Thanks Upgrading to 1.22.1 solved the issue
